name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  test-and-build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: ""
          
          - os: windows-latest
            ext: ".exe"
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - run: cargo test --verbose
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: "paradeiser${{ matrix.ext }}"
        path: "target/release/paradeiser${{ matrix.ext }}"